---
# defaults file for mailadmin

ubuntu_packages_list:
  - php-ldap
  - slapd
  - ldap-utils
  - debconf-utils

packages_dir: /packages
postfix_public_dir: public
template_c_dir: templates_c
mailadmin_directory_name: emailadmin
mailadmin_version: postfixadmin-3.3.10
mailadmin_repository: https://github.com/wolfman68/vMailpanel.git
mailadmin_webfolder: /var/www/html/{{ mailadmin_directory_name }}


database_type: mysqli
postfix_database_name: postfix
mailadmin_root_folder: /packages/{{ mailadmin_directory_name }}
mailadmin_php_local_config_file: config.local.php

postfix_password_encryption_protocol: md5crypt

site_domain: ldap.gomail.life
countryname: CM
support_email: blionnel15@gmail.com
organizationname: gomailia
organizationalunitname: mailservice

apache2_alias_regexp_line: '        Alias /{{ mailadmin_directory_name }}'
apache2_servername_regexp_line: '        ServerName '
apache2_servername_line_mailadmin: '        ServerName {{ site_domain }}'
apache2_alias_line_mailadmin: '        Alias /{{ mailadmin_directory_name }} {{ mailadmin_webfolder }}/{{ postfix_public_dir }}'


vmailpanel_schema_folder: '{{ mailadmin_root_folder }}/schema/'
ldap_schema_folder: /etc/ldap/schema
schemas_to_load:
  - '{{ ldap_schema_folder }}/vmail.ldif'
  - '{{ ldap_schema_folder }}/ISPEnv2.ldif'
  - '{{ ldap_schema_folder }}/amavis.ldif'
  - '{{ ldap_schema_folder }}/pureftpd.ldif'
  - '{{ ldap_schema_folder }}/perversia.net.ldif'
acls_to_load:
  - '{{ ldap_schema_folder }}/acl-remove.ldif'
  - '{{ ldap_schema_folder }}/acl-new.ldif'
admin_root_dn: 'cn=admin'
admin_root_user: admin
top_level_domain: life
root_domain: gomail
ldap_root_domain: gomail.life
hosting_ou: hosting
ldap_database_backend: MDB
ldap_no_configuration: false
ldap_purge_database: true
ldap_move_old_database: true
ldap_organization: gomail.life
vmail_account: vmail
base_ldif_file: base.ldif