---


- name: copy map configuration files
  template:
    src: '{{ item }}.j2'
    dest: '{{ postfix_config_directory }}/{{ item }}'
    group: postfix
    mode: '0640'
  loop: '{{ ldap_configuration_files_list }}'
  notify:
    - restart postfix service
  tags:
    - map_config_file

- name: create virtual mail system group
  group:
    name: '{{ vmail_system_user }}'
    state: present
  tags:
    - create_user
    
- name: create virtual mail system user
  user:
    name: '{{ vmail_system_user }}'
    group: '{{ vmail_system_user }}'
    groups: '{{ vmail_groups }}'
    home: /home/{{ vmail_system_user }}
  tags:
    - create_user
    
- name: Get postfix system user '{{ vmail_system_user }}' user info
  getent:
    database: passwd
    key: '{{ vmail_system_user }}'
  tags:
    - create_user

- name: configure postfix with ldap maps
  blockinfile:
    path: '{{ postfix_config_file }}'
    block: |
      {{ virtual_mailbox_domain_settings }}
  notify:
    - restart postfix service
  tags:
    - postfix_ldap

- name: configure spectific parameter of postfix
  lineinfile:
    path: '{{ postfix_config_file }}'
    regexp: '^myhostname ='
    line: myhostname = {{ mailserver_hostname }}
  tags:
    - postfix_ldap
  notify: 
    - restart postfix service

- name: modify postfix main config file for dovecot lmtp
  lineinfile:
    regexp: '{{ item.targetline }}' 
    path: '{{ postfix_config_file }}'
    line: '{{ item.targetconfig }}'
    backup: yes
  with_items:
    - {targetline: '^virtual_transport =', targetconfig: 'virtual_transport = lmtp:{{ inventory_hostname }}:{{ lmtp_port }}'}
    - {targetline: '^smtputf8_enable =', targetconfig: 'smtputf8_enable = no'}
  notify:
    - restart postfix service
  tags:
    - postfix_config
    - now1

- name: modify postfix main config file for dovecot auth service
  lineinfile:
    regexp: '{{ item.targetline }}'
    path: '{{ postfix_config_file }}'
    line: '{{ item.targetconfig }}'
    backup: yes
  with_items:
    - {targetline: 'smtpd_sasl_path =', targetconfig: 'smtpd_sasl_path = inet:{{ inventory_hostname }}:{{ dovecot_auth_port }}'}
    - {targetline: 'smtpd_sasl_type =', targetconfig: 'smtpd_sasl_type = dovecot'}
    - {targetline: 'smtpd_sasl_auth_enable =', targetconfig: 'smtpd_sasl_auth_enable = yes'}
    - {targetline: 'default_transport = smtp', targetconfig: 'default_transport = smtp'}
  notify:
    - restart postfix service
  tags:
    - postfix_config
    - now1

- name: enable submission service on postfix
  lineinfile:
    path: '{{ postfix_master_config_file }}'
    regexp: '{{ enable_submission_service_line.from }}'
    line: '{{ enable_submission_service_line.to }}'
    backup: yes
  notify:
    - restart postfix service
  tags:
    - postfix_config
  
- name: copy gnarwl template configuration file
  template:
    src: '{{ gnarwl_config_file }}.j2'
    dest: '{{ gnarwl_config_folder }}/{{ gnarwl_config_file }}'
    backup: yes
    owner: '{{ vmail_system_user }}'
    group: '{{ vmail_system_user }}'
  tags:
    - gnarwl_config

- name: copy postfix transport template configuration file
  template:
    src: '{{ transport_config_file }}.j2'
    dest: '{{ postfix_config_directory }}/{{ transport_config_file }}'
    backup: yes
  tags:
    - postfix_config

- name: create de transport db
  shell:
    cmd: postmap {{ postfix_config_directory }}/{{ transport_config_file }}
  tags:
    - postfix_config


- name: Check if apache service is present on system
  stat: 
    path: '{{lib_services_folder}}/{{ apache_service_name }}'
  register: service_status
  tags:
    - postfix_config

- name: stop apache service
  service:
    name: '{{ apache_service_name }}'
    state: stopped
  when: service_status.stat.exists
  notify:
    - restart apache service
  tags:
    - postfix_config

- name: generate certificate for mailserver service
  shell:
    cmd: > 
      certbot
      certonly
      --standalone
      --non-interactive
      --agree-tos
      -m {{ support_email }}
      -d {{ site_smtp_domain }}
  args:
    chdir: '{{ cert_folder_path }}/{{ private_cert_folder_name }}'
  tags:
    - postfix_config

- name: configure smtp service with tls
  lineinfile:
    path: '{{ postfix_config_file }}'
    regexp: '{{ item.from }}'
    line: '{{ item.to }}'
  with_items: '{{ smtp_tls_target_config }}'
  notify:
    - restart postfix service
  tags:
    - postfix_config

- name: open firewall ports for mailserver
  ufw:
    default: reject
    log: yes
    proto: '{{ item.protocol }}'
    rule: '{{ item.rule }}'
    state: enabled
    to_port: '{{ item.port }}'
  with_items: '{{ target_ufw_config }}'
  tags:
    - firewall