---
# defaults file for seafile

ubuntu_packages_list:
  - mariadb-server
  - python3 
  - python3-pip 
  - python3-pil 
  - python3-ldap 
  - python3-urllib3 
  - python3-setuptools 
  - python3-mysqldb 
  - python3-memcache 
  - python3-requests
  - ffmpeg 
  - memcached 
  - libmemcached-dev
