---
# defaults file for mailserver

ubuntu_packages_list:
  - postfix
  - postfix-ldap
  - libsasl2-modules
  - openssl
  - certbot
  - gnarwl




ldap_configuration_files_list:
  - '{{ ldap_account_conf_file }}'
  - '{{ ldap_accountmap_conf_file }}'
  - '{{ ldap_aliases_conf_file }}'
  - '{{ ldap_transport_conf_file }}'
  - '{{ ldap_vacation_conf_file }}'
  - '{{ ldap_virtualforward_conf_file }}'
  - '{{ ldap_virtual_domain_conf_file }}'

postfix_config_directory: /etc/postfix


postfix_database_name: postfix
database_alias_table: alias
database_domain_table: domain
database_mailbox_table: mailbox
database_quota_table: mailbox
database_relay_domain_table: domain
alias_select_field: goto
alias_where_field: address
domain_select_field: domain
domain_where_field: domain
mailbox_select_field: maildir
mailbox_where_field: username
quota_select_field: quota
quota_where_field: username
relay_domain_select_field: domain
relay_domain_where_field: domain

vmail_system_user: vmail
vmail: test
vmail_groups: 
  - sasl

virtual_mailbox_domain_settings: |
  # Virtual Mailbox Domain Settings

  # transport_maps
  maildrop_destination_concurrency_limit = 2 
  maildrop_destination_recipient_limit = 1
  gnarwl_destination_concurrency_limit = 1 
  gnarwl_destination_recipient_limit = 1

  virtual_alias_maps = 
    ldap:{{ postfix_config_directory }}/{{ ldap_aliases_conf_file }}
    ldap:{{ postfix_config_directory }}/{{ ldap_virtualforward_conf_file }}
    ldap:{{ postfix_config_directory }}/{{ ldap_accountmap_conf_file }}
    
  # virtual accounts for delivery
  virtual_mailbox_base = /home/{{ vmail_system_user }}
  virtual_mailbox_maps = ldap:{{ postfix_config_directory }}/{{ ldap_account_conf_file }}
  virtual_mailbox_domains = ldap:{{ postfix_config_directory }}/{{ ldap_virtual_domain_conf_file }}
  local_recipient_maps = $alias_maps

  recipient_bcc_maps = ldap:{{ postfix_config_directory }}/{{ ldap_vacation_conf_file }}

  virtual_mailbox_limit = 51200000
  virtual_minimum_uid = {{ system_virtual_minimum_uid }}
  virtual_uid_maps = static:{{ getent_passwd[vmail_system_user].1 }}
  virtual_gid_maps = static:{{ getent_passwd[vmail_system_user].2 }}


system_virtual_minimum_uid: 1000
postfix_config_file: '{{ postfix_config_directory }}/main.cf'
postfix_master_config_file: '{{ postfix_config_directory }}/master.cf'
mailserver_hostname: '{{ site_smtp_domain }}'

enable_submission_service_line:
  from: '^#submission inet n       -       y       -       -       smtpd' 
  to: 'submission inet n       -       y       -       -       smtpd'

lmtp_port: 24
dovecot_auth_port: 12345

letsencrypt_cert_folder: /etc/letsencrypt/archive
site_smtp_domain: smtp.ldap.gomail.life
cert_folder_path: /etc/pki/cert
private_cert_folder_name: private
csr_key_file_name :  '{{ site_imap_domain }}_csr.key'
support_email: blionnel15@gmail.com
lib_services_folder: /lib/systemd/system
apache_service_name: apache2.service
smtp_tls_target_config:
  - {from: '^smtpd_tls_cert_file=', to: 'smtpd_tls_cert_file={{ letsencrypt_cert_folder }}/{{ site_smtp_domain }}/fullchain1.pem'}
  - {from: '^smtpd_tls_key_file=', to: 'smtpd_tls_key_file={{ letsencrypt_cert_folder }}/{{ site_smtp_domain }}/privkey1.pem'}

# ldap variables
ldap_server: ec2-18-118-48-144.us-east-2.compute.amazonaws.com
ldap_server_port: 389
ldap_protocol_version: 3
ldap_vmail_user: vmail
ldap_admin_user: admin
ldap_top_level_domain: life
ldap_root_domain: gomail
ldap_root_organization: hosting
ldap_base_domain: dc={{ ldap_root_domain }},dc={{ ldap_top_level_domain }}
ldap_bin_dn_user: cn={{ ldap_vmail_user }},o={{ ldap_root_organization }},dc={{ ldap_root_domain }},dc={{ ldap_top_level_domain }}
ldap_bin_admin_user: cn={{ ldap_admin_user }},o={{ ldap_root_organization }},dc={{ ldap_root_domain }},dc={{ ldap_top_level_domain }}
ldap_search_base_dn: o={{ ldap_root_organization }},dc={{ ldap_root_domain }},dc={{ ldap_top_level_domain }}

ldap_account_conf_file: ldap-accounts.cf
ldap_accountmap_conf_file: ldap-accounstmap.cf
ldap_aliases_conf_file: ldap-aliases.cf
ldap_transport_conf_file: ldap-transport.cf
ldap_vacation_conf_file: ldap-vacation.cf
ldap_virtualforward_conf_file: ldap-virtualforward.cf
ldap_virtual_domain_conf_file: ldap_virtual_domains.cf

gnarwl_config_folder: /etc
gnarwl_config_file: gnarwl.cfg
transport_config_file: transport