---


- name: extract roundcube package archive
  unarchive:
    remote_src: yes
    src: '{{ packages_folder }}/{{ roundcube_package }}'
    dest:  '{{ packages_folder }}'
    owner: '{{ webmail_system_user }}'
    group: '{{ webmail_system_user }}'
  tags:
    - roundcube_config


- name: create roundcube website directory
  file:
    path: '{{ apache2_root_folder }}/{{ roundcube_folder_name }}'
    state: directory
    owner: '{{ webmail_system_user }}'
    group: '{{ webmail_group_user }}'
    mode: '774'
    recurse: yes
  tags:
    - roundcube_config

- name: create roundcube website
  copy:
    remote_src: yes
    src: '{{ packages_folder }}/{{ roundcube_extracted_folder_name }}'
    dest: '{{ apache2_root_folder }}/{{ roundcube_folder_name }}'
    owner: '{{ webmail_system_user }}'
    group: '{{ webmail_group_user }}'
  tags:
    - roundcube_install

- name: create roundcube configuration file
  template:
    src: '{{ roundcube_config_file_name }}.j2'
    dest: '{{ roundcube_config_file_path }}'
    owner: '{{ webmail_system_user }}'
    group: '{{ webmail_group_user }}'
  tags:
    - roundcube_install

- name: copy database creation script
  copy:
    src: createdb.sql
    dest: /tmp
  tags:
    - roundcube_config

- name: create roundcube database and database user
  shell:
    cmd: mysql -h {{ database_host }} -u {{ database_root_user }}  < /tmp/createdb.sql
  environment:
    MYSQL_PWD: '{{ database_root_password }}'
  run_once: true
  tags:
    - roundcube_config

- name: change database initialization script
  copy:
    src: '{{ mysql_initialize_roundcube_script }}'
    dest: '{{ apache2_root_folder }}/{{ roundcube_folder_name }}/{{ roundcube_sql_script_folder }}'
    backup: yes
  tags:
    - roundcube_config

- name: intialize roundcube database
  shell:
    cmd: mysql -h {{ database_host }} -u {{ database_rw_user }}  {{ database_name }} < {{ apache2_root_folder }}/{{ roundcube_folder_name }}/{{ roundcube_initialize_db_script }}
  environment:
    MYSQL_PWD: '{{ database_rw_password }}'
  run_once: true
  tags:
    - roundcube_config

- name: set php data.timezone
  lineinfile:
    path: '{{ php_config_file }}'
    insertafter: ';date.timezone ='
    line: 'date.timezone = {{ time_zone }}'
  notify:
    - restart apache2 service
  tags:
    - roundcube_config

- name: download custom skins for roundcube
  ansible.builtin.git:
    force: yes
    repo: '{{ item.url }}'
    dest: '{{ roundcube_skin_directory }}/{{ item.skin_name }}'
  become_user: '{{ webmail_system_user }}'
  become: true
  with_items: '{{ custom_skin_list }}' 
  vars:
    allow_world_readable_tmpfiles: true
  tags:
    - roundcube_config
    - now
    - test

- name: download custom skins for roundcube to {{ roundcube_temp_directory }}
  ansible.builtin.git:
    repo: '{{ item.url }}'
    dest: '{{ roundcube_temp_directory }}/{{ item.skin_name }}' 
  with_items: '{{ special_custom_skin_list }}' 
  tags:
    - roundcube_config
    - now
    - test

- name: enable custom skins from {{ roundcube_temp_directory }} folder
  copy: 
    remote_src: yes
    src: '{{ item.local_temp_folder }}/' 
    dest: '{{ roundcube_skin_directory }}/{{ item.skin_name }}'
    owner: '{{ webmail_system_user }}'
    group: '{{ webmail_system_user }}'
  with_items: '{{ special_custom_skin_list }}'
  tags:
    - roundcube_config
    - now

- name: change default skin for roundcube
  lineinfile:
    path: '{{ roundcube_default_config_file }}'
    regexp: '^\$config\[''skin''\] ='
    line: "$config['skin'] = '{{ default_skin }}';"
  tags:
    - roundcube_config
    - now

