---

- name: update apt packages cache
  apt:
    update_cache: yes
  tags:
    - install

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ ubuntu_packages_list }}"
  tags:
    - install
    - install_package

- name: install python libraries
  pip:
    name: '{{ item }}'
  loop: "{{ python_packages_list }}"
  tags:
    - install
    - install_package