---
# handlers file for mailadmin

- name: restart apache2 service
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Restart cron service
  service:
    name: cron
    state: restarted
    enabled: yes

- name: restart ldap service
  service:
    name: slapd
    state: restarted
    enabled: yes