---
# handlers file for imapserver

- name: restart dovecot service
  service:
    name: dovecot
    state: restarted
    enabled: yes

- name: restart apache service
  service:
    name: apache2
    state: restarted
    enabled: yes